version: '3'

services:
  jenkins:
    image: jenkins-ci:v2
    ports:
      - "8090:8080"
      - "50001:50000"
    volumes:
      - ~/util/fast_campus/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
